#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif

enum ELayers {
    BASE_QWERTY     = 0,
    BASE_COLEMAK_DH = 1,
    NUMBER          = 2,
    FUNC            = 3,
    NAV             = 4,
    SYMBOL          = 5,
    MOUSE           = 6,
    MEDIA           = 7,
    FPS             = 8,
};

// Define layers above this so that we can benefit from enum values
#if __has_include("g/keymap_combo.h")
#    include "g/keymap_combo.h"
#endif

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

// clang-format off
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
[BASE_QWERTY] = LAYOUT_split_3x6_3_ex2(
    //|----------------+----------------+----------------+----------------+----------------+----------------+----------------,  ,----------------+----------------+----------------+----------------+----------------+----------------+----------------|
        KC_LCBR,         KC_Q,            KC_W,            KC_E,            KC_R,            KC_T,            KC_NO,              KC_NO,           KC_Y,            KC_U,            KC_I,            KC_O,            KC_P,            KC_RCBR,
    //|----------------+----------------+----------------+----------------+----------------+----------------+----------------|  |----------------+----------------+----------------+----------------+----------------+----------------+----------------|
        KC_LPRN,        LGUI_T(KC_A),    LALT_T(KC_S),     LCTL_T(KC_D),   LSFT_T(KC_F),    KC_G,            KC_NO,              KC_NO,           KC_H,            RSFT_T(KC_J),    RCTL_T(KC_K),     RALT_T(KC_L),    RGUI_T(KC_QUOT), KC_RPRN,
    //|----------------+----------------+----------------+----------------+----------------+----------------+----------------'  '----------------+----------------+----------------+----------------+----------------+----------------+----------------|
        KC_LT,          KC_Z,            KC_X,            KC_C,            KC_V,            KC_B,                                                 KC_N,            KC_M,            KC_COMM,         KC_DOT,          KC_UNDS,         KC_GT,
    //|----------------+----------------+----------------+----------------+----------------+----------------+----------------,  ,----------------+----------------+----------------+----------------+----------------+----------------+----------------|
                                                                          LT(MEDIA,KC_TAB), LT(NAV,KC_ESC),  LT(MOUSE,KC_SPC),   LT(SYMBOL,KC_ENT),LT(NUMBER,KC_BSPC),LT(FUNC,KC_DEL)
                                                                      //'----------------------------------------------------'  '----------------------------------------------------'
    ),

[BASE_COLEMAK_DH] = LAYOUT_split_3x6_3_ex2(
    //|----------------+----------------+----------------+----------------+----------------+----------------+----------------,  ,----------------+----------------+----------------+----------------+----------------+----------------+----------------|
        KC_LCBR,         KC_Q,            KC_W,            KC_F,            KC_P,            KC_B,            KC_NO,              KC_NO,           KC_J,            KC_L,            KC_U,            KC_Y,            KC_QUOT,        KC_RCBR,
    //|----------------+----------------+----------------+----------------+----------------+----------------+----------------|  |----------------+----------------+----------------+----------------+----------------+----------------+----------------|
        KC_LPRN,        LGUI_T(KC_A),    LALT_T(KC_R),     LCTL_T(KC_S),   LSFT_T(KC_T),    KC_G,            KC_NO,              KC_NO,           KC_M,            RSFT_T(KC_N),    RCTL_T(KC_E),     RALT_T(KC_I),    RGUI_T(KC_O),   KC_RPRN,
    //|----------------+----------------+----------------+----------------+----------------+----------------+----------------'  '----------------+----------------+----------------+----------------+----------------+----------------+----------------|
        KC_LT,          KC_Z,            KC_X,            KC_C,            KC_D,            KC_V,                                                 KC_K,            KC_H,            KC_COMM,         KC_DOT,          KC_UNDS,         KC_GT,
    //|----------------+----------------+----------------+----------------+----------------+----------------+----------------,  ,----------------+----------------+----------------+----------------+----------------+----------------+----------------|
                                                                          LT(MEDIA,KC_TAB), LT(NAV,KC_ESC),  LT(MOUSE,KC_SPC),   LT(SYMBOL,KC_ENT),LT(NUMBER,KC_BSPC),LT(FUNC,KC_DEL)
                                                                      //'----------------------------------------------------'  '----------------------------------------------------'
    ),
[NUMBER] = LAYOUT_split_3x6_3_ex2(//  KC_PSLS, KC_1, KC_2, KC_3, KC_PMNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
    //|----------------+----------------+----------------+----------------+----------------+----------------+----------------,  ,----------------+----------------+----------------+----------------+----------------+----------------+----------------|
        KC_NO,          KC_PAST,         KC_7,            KC_8,            KC_9,            KC_PLUS,         KC_NO,              KC_NO,           KC_NO,           KC_NO,           KC_NO,           KC_NO,           KC_NO,           KC_NO,
    //|----------------+----------------+----------------+----------------+----------------+----------------+----------------|  |----------------+----------------+----------------+----------------+----------------+----------------+----------------|
        KC_NO,          KC_0,            KC_4,            KC_5,            KC_6,            KC_PEQL,         KC_NO,              KC_NO,           KC_NO,           KC_NO,           KC_NO,           KC_NO,           KC_NO,           KC_NO,
    //|----------------+----------------+----------------+----------------+----------------+----------------+----------------'  '----------------+----------------+----------------+----------------+----------------+----------------+----------------|
        KC_NO,          KC_PSLS,         KC_1,            KC_2,            KC_3,            KC_PMNS,                                              KC_NO,           KC_NO,           KC_NO,           KC_NO,           KC_NO,           KC_NO,
    //|----------------+----------------+----------------+----------------+----------------+----------------+----------------,  ,----------------+----------------+----------------+----------------+----------------+----------------+----------------|
                                                                           KC_TAB,          KC_ESC,          KC_SPC,             KC_NO,           KC_NO,           KC_NO
                                                                      //'----------------------------------------------------'  '----------------------------------------------------'
    ),
[FUNC] = LAYOUT_split_3x6_3_ex2(KC_NO, KC_F12, KC_F7, KC_F8, KC_F9, KC_PSCR, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_F11, KC_F4, KC_F5, KC_F6, KC_SCRL, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_F10, KC_F1, KC_F2, KC_F3, KC_PAUS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
[NAV] = LAYOUT_split_3x6_3_ex2(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_CAPS, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_INS, KC_HOME, KC_PGDN, KC_PGUP, KC_END, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
[SYMBOL] = LAYOUT_split_3x6_3_ex2(KC_NO, KC_GRV, KC_AMPR, KC_ASTR, KC_LPRN, KC_PLUS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_QUES, KC_DLR, KC_PERC, KC_CIRC, KC_PEQL, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_PSLS, KC_EXLM, KC_AT, KC_HASH, KC_PMNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
[MOUSE] = LAYOUT_split_3x6_3_ex2(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, MS_LEFT, MS_DOWN, MS_UP, MS_RGHT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, MS_WHLL, MS_WHLD, MS_WHLU, MS_WHLR, KC_NO, KC_NO, KC_NO, KC_NO, MS_BTN1, MS_BTN2, MS_BTN3),
[MEDIA] = LAYOUT_split_3x6_3_ex2(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_MPRV, KC_VOLD, KC_VOLU, KC_MNXT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_MPLY, KC_MSTP, KC_MUTE),
[FPS] = LAYOUT_split_3x6_3_ex2(KC_ESC, KC_T, KC_Q, KC_W, KC_E, KC_R, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TAB, KC_G, KC_A, KC_S, KC_D, KC_F, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LALT, KC_B, KC_Z, KC_X, KC_C, KC_V, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LCTL, KC_LSFT, KC_SPC, KC_NO, KC_NO, KC_NO)
};
// clang-format on

// Key overrides
const key_override_t lparen_override = ko_make_basic(MOD_MASK_SHIFT, KC_LPRN, KC_LBRC);
const key_override_t rparen_override = ko_make_basic(MOD_MASK_SHIFT, KC_RPRN, KC_RBRC);
const key_override_t comma_override  = ko_make_basic(MOD_MASK_SHIFT, KC_COMM, KC_SCLN);
const key_override_t period_override = ko_make_basic(MOD_MASK_SHIFT, KC_DOT, KC_COLN);
const key_override_t unds_override   = ko_make_basic(MOD_MASK_SHIFT, KC_UNDS, KC_PIPE);

const key_override_t *key_overrides[] = {&lparen_override, &rparen_override, &comma_override, &period_override, &unds_override};

// // Key combos
// enum _combos { QW_TILDE };
//
// const uint16_t PROGMEM ab_combo[] = {KC_A, KC_B, COMBO_END};
//
// combo_t key_combos[] = {
//     [QW_TILDE] = COMBO(ab_combo, KC_ESC),
// };

// Chordal hold handedness
// clang-format off
const char chordal_hold_layout[MATRIX_ROWS][MATRIX_COLS] PROGMEM =
    LAYOUT_split_3x6_3_ex2(
        'L', 'L', 'L', 'L', 'L', 'L', 'L',  'R', 'R', 'R', 'R', 'R', 'R', 'R',
        'L', 'L', 'L', 'L', 'L', 'L', 'L',  'R', 'R', 'R', 'R', 'R', 'R', 'R',
        'L', 'L', 'L', 'L', 'L', 'L',            'R', 'R', 'R', 'R', 'R', 'R',
                            'L', 'L', 'L',  'R', 'R', 'R'
    );
// clang-format on

#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C
